name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - uses: astral-sh/setup-uv@v1
        with:
          version: "latest"
      - name: uv version check
        run: uv version
      - name: run example using uv 
        run: |
            echo 'import requests; print(requests.get("https://astral.sh"))' > example.py
            uv add --script example.py requests
            uv run example.py
      - name: uv python
        run: uv python pin 3.11
      - name: python list check
        run: uv python list
      - name: uv venv install
        run: uv pip install -e .   
      
